### ISSUE TITLE
干的漂亮，妥妥的干货！

### ISSUE THREAD

**Issue by liutianling** [fourierer/classification_of_ImageNet_Resnet_Pytorch#1]

**Comment by fourierer** [comment]
@liutianling 谢谢~这个repo感觉写的很乱，几个并行训练方法可以参考 https://github.com/fourierer/Training_model_with_Data_Parallelism ，其中给出了三种并行训练代码和pytorch官方的集成代码，里面也有一些较为详细的解释。
